# Site settings
title: Yangjiao Chen                    #你博客的标题
header-img: static/yangjiaochen.jpg     #显示在首页的背景图片
email: ychen3254@gamil.com    
url: "https://yangjiaochen.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
